// <auto-generated />
namespace OBE_BLL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PEOPrograms_Created : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PEOPrograms_Created));
        
        string IMigrationMetadata.Id
        {
            get { return "202107071759431_PEOPrograms_Created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
